// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHEOLLWzEZu8KFkhtHw39ewYiLZAnOKzc',
    appId: '1:943538294556:web:f2b71b35e5a55eaff574d9',
    messagingSenderId: '943538294556',
    projectId: 'simple-recipe-keeper-66731',
    authDomain: 'simple-recipe-keeper-66731.firebaseapp.com',
    storageBucket: 'simple-recipe-keeper-66731.firebasestorage.app',
    measurementId: 'G-ZWW2N645HD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy-ZVw3b3xm2WFJLYa0nFTItsxCWKUDdA',
    appId: '1:943538294556:android:353e0503747378b0f574d9',
    messagingSenderId: '943538294556',
    projectId: 'simple-recipe-keeper-66731',
    storageBucket: 'simple-recipe-keeper-66731.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANwIscAGivPAjHkIz-9f7gYwujq4-7Uv8',
    appId: '1:943538294556:ios:9fd6c857b78b8b4af574d9',
    messagingSenderId: '943538294556',
    projectId: 'simple-recipe-keeper-66731',
    storageBucket: 'simple-recipe-keeper-66731.firebasestorage.app',
    iosBundleId: 'com.example.uasC14210002',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANwIscAGivPAjHkIz-9f7gYwujq4-7Uv8',
    appId: '1:943538294556:ios:9fd6c857b78b8b4af574d9',
    messagingSenderId: '943538294556',
    projectId: 'simple-recipe-keeper-66731',
    storageBucket: 'simple-recipe-keeper-66731.firebasestorage.app',
    iosBundleId: 'com.example.uasC14210002',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHEOLLWzEZu8KFkhtHw39ewYiLZAnOKzc',
    appId: '1:943538294556:web:a87313eb2c29e1b3f574d9',
    messagingSenderId: '943538294556',
    projectId: 'simple-recipe-keeper-66731',
    authDomain: 'simple-recipe-keeper-66731.firebaseapp.com',
    storageBucket: 'simple-recipe-keeper-66731.firebasestorage.app',
    measurementId: 'G-CSVCFFQ05L',
  );

}